version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: lottery
      MYSQL_USER: lottery
      MYSQL_PASSWORD: F4UnYPAGK7fvinFJGnnmtMSJ8DKnBhBS
      MYSQL_ROOT_PASSWORD: I6yNfRH70SBgBvDqdeHXqTZLVFrf1E7h
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: php
    volumes:
      - ./src:/var/www/html
    # ports:
    #   - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    ipam:
      config:
        - subnet: 172.16.88.0/24
